### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by smithtim** [ruby/set#12]
For Ruby 2.7.2, online documentation for this library was at ruby-doc:

https://ruby-doc.org/stdlib-2.7.2/libdoc/set/rdoc/Set.html

But I cannot find it there for Ruby 3.0.0:

https://ruby-doc.org/stdlib-3.0.0/

Has it moved somewhere else?

**Comment by hsbt** [comment]
Please contact the admin of ruby-doc.org. It's an unofficial.
